pub const DEFAULT_WINDOW_WIDTH = 1280;
pub const DEFAULT_WINDOW_HEIGHT = 720;
pub const MAX_KEYBOARD_KEYS = 350;
pub const MAX_SOUND_CHANNELS = 16;

pub const PLAYER_SPEED = 4.0 / @intToFloat(f32, DEFAULT_WINDOW_WIDTH);
pub const PLAYER_BULLET_SPEED = 16.0 / @intToFloat(f32, DEFAULT_WINDOW_WIDTH);
