pub const DEFAULT_WINDOW_WIDTH = 1280;
pub const DEFAULT_WINDOW_HEIGHT = 720;
pub const MAX_KEYBOARD_KEYS = 350;
pub const MAX_MOUSE_BUTTONS = 5;
pub const MAX_SOUND_CHANNELS = 16;

pub const PLAYER_SPEED = 8.0 / @intToFloat(f32, DEFAULT_WINDOW_WIDTH);
pub const ENEMY_SPEED = 16.0 / @intToFloat(f32, DEFAULT_WINDOW_WIDTH);

pub const PLAYER_SCALE = 0.25;
